#include <iostream>

using namespace std;

int main(){

    int num = 10;
    cout<< num <<"\n\n";

    num = num * -1;
    cout<< num <<"\n\n";

    int num2 = 50;
    cout<< -num2 <<"\n\n";
    cout<< num2 <<"\n\n";

    num = 10;
    num -=10;
    cout<< num <<"\n\n";

    num =-num;
    cout<< num <<"\n\n";


    int num3 = 100;
    num3 -= 10;    
    cout<< num3 <<"\n\n";
    cout<< num3 <<"\n\n";
    num3 += 10;    
    cout<< num3 <<"\n\n";



    return 0;
}